[project]
name = "kotak-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "neo-api-client",
    "notebook>=7.6.2",
    "pyotp>=2.10.0",
    "pyspark>=4.2.0",
]

[tool.uv.sources]
neo-api-client = { git = "https://github.com/Kotak-Neo/Kotak-neo-api-v2.git", rev = "v2.0.2" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
